In [1]:
import numpy as np

# Create matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Addition
print("Addition:\n", A + B)

# Subtraction
print("Subtraction:\n", A - B)

# Matrix Multiplication
print("Multiplication:\n", np.dot(A, B))

# Transpose
print("Transpose of A:\n", A.T)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]


In [2]:
import numpy as np

# Generate random array
arr = np.random.rand(10)

print("Array:", arr)
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))

Array: [0.10557255 0.95987503 0.89595536 0.61341273 0.37230416 0.48981002
 0.24983464 0.79681514 0.043541   0.72649985]
Mean: 0.5253620482204211
Standard Deviation: 0.30935704506254336
Minimum: 0.04354100037199593
Maximum: 0.959875027890452
