In [ ]:
import statistics

numbers = [10, 20, 30, 40, 50, 20]

# Mean
mean = statistics.mean(numbers)

# Median
median = statistics.median(numbers)

# Mode
mode = statistics.mode(numbers)

# Variance
variance = statistics.variance(numbers)

# Standard Deviation
std_dev = statistics.stdev(numbers)

print("Mean:", mean)
print("Median:", median)
print("Mode:", mode)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

Mean: 28.333333333333332
Median: 25.0
Mode: 20
Variance: 216.66666666666666
Standard Deviation: 14.719601443879744


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# Sum and Mean
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))

# Maximum and Minimum
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

# Reshape array (2 rows, 3 columns)
reshaped = arr.reshape(2, 3)
print("Reshaped Array:\n", reshaped)

# Element-wise multiplication
result = arr * 2
print("Element-wise Multiplication:\n", result)

Sum: 21
Mean: 3.5
Maximum: 6
Minimum: 1
Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Element-wise Multiplication:
 [ 2  4  6  8 10 12]
